# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 929f97f3c791b9f4cd8cd3a32ddc52dbc352a2c772c8a02f6fbc159b0d2d2cf2c5b77a5a6eeec0e5e7297b59f165be0eb41e9b400cdc5c042daa1c6344d7579d

test:
  secret_key_base: 02faa1cca8aeb2820b1e3b63298c1f3d369489118ddd3d329e23a14cb1b7bea7a115cbc81113566125bd60971cddf092a6042e45bd482d5cad30752187410971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
